#include<iostream>
#include<cstdlib>

using namespace std;

int main()
    {
    system("clear");
    srand(time(NULL));
    int randomNo, guessNo,n=1,t=1;
    randomNo = rand()%1000+1;
    cout<<"Hello Player. We would be playing a guessing game."<<endl<<"The Rules are simple."<<endl<<"You just have to guess a number between 1-1000."<<endl;
    cout<<"The computer will then inform you about your guess."<<endl;
    cout<<"So Lets Start"<<endl<<endl;
    do
        {
        if(t==1)cout<<"Make Your Guess..";
        if(t==2)
            {
            cout<<"Select a number between 1 and 1000"<<endl;
            cout<<"Make a guess Again"<<endl;
            }
        cin>>guessNo;
        t=2;
        }while(guessNo<1 || guessNo>1000);

    do
        {
         if(guessNo<randomNo) cout<<"The Number you selected is small. Select a bigger number"<<endl;
         if(guessNo>randomNo) cout<<"The Number you selected is big. Select a smaller Number"<<endl;
         if(guessNo==randomNo)
            {
            cout<<"Your guess is right . The random Number Generated by the computer is "<<randomNo<<endl;
            break;
            }
         cout<<"Guess a number again...";
         if(guessNo>0 && guessNo<1000) cin>>guessNo;
            else cout<<endl<<"Invalid choice(Please select a number in the range).";
         if(n==10) cout<<"This will be your last try.."<<endl;
         n++;
        }while(n<12);

        if(n==12)
            {
            cout<<endl<<"Sorry you lost.Try Again."<<endl<<endl;
            cout<<"The number generated by the computer is: "<<randomNo;
            }



    }
